name: MultiRodTrigger
version: 'Beta-1.0.1-SNAPSHOT'
main: me.rtx4090.multiRodTrigger.MultiRodTrigger
api-version: '1.21'
authors: [ RTX4090 ]
description:
permissions:
    multirodtrigger.op:
        description: Allows the player to use debug command
        default: op
